version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - data:/pb_data
      - public:/pb_public

  vite:
   image: node:latest
   container_name: vite
   ports:
     - 5173:5173
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   command: bash -c "npm i & npm run dev"
   restart: always
   tty: true

volumes:
  data:
  public: